### ISSUE TITLE
New wallet created but old wallet used

### ISSUE THREAD

**Issue by betaboot** [GooBox/goobox-community-gui#100]
Unfortunately, i am not sure anymore what excact steps i did to end up in this situation. What i remember is this:

- I installed Goobox the first time and it gave me a new Sia address and seed.
- Because i had some problems during installation (see #96), i uninstalled it again.
- Could be that i manually deleted some files as well because i saw that not all files were deleted automatically.
- Afterwards, i installed Goobox again and it gave me another address and seed.
- Then i sent some SC to the new address but the coins never showed up.
- After some hours i sent some coins to the old address and they showed up in the wallet.

So it seems that Goobox created a new seed but then still used the old wallet.

**Comment by MeijeSibbel** [comment]
I was not able to reproduce this. If you are able to reproduce it please let us know and i will reopen the issue, thanks.
