### ISSUE TITLE
Moving a folder with a file inside does not sync again

### ISSUE THREAD

**Issue by betaboot** [GooBox/goobox-community-gui#107]
### Versions
- **GUI Version:** v0.1.2
- **Operating System:** windows 10
- **Storage provider selected:** Sia

### Actual Behavior

If i move a file from one folder to the other, then it will sync again in the new folder --> OK
But if i move a folder with a file in it to a new folder, then the file will not sync again until Goobox is restarted.

### Steps to Reproduce

1. Create two folders F1 and F2.
2. Place two files A and B into folder F1 and let them sync.
3. Move file A into folder F2 --> File A will sync.
4. Move folder F1 with file B in it into folder F2. --> File B will not sync.

**Comment by jkawamoto** [comment]
Thank you for reporting this issue. I could reproduce it.

**Comment by jkawamoto** [comment]
This one https://github.com/gmethvin/directory-watcher/issues/10 seems to cause this issue.

**Comment by jkawamoto** [comment]
Fixed in [v0.1.4](https://github.com/GooBox/goobox-community-gui/releases/tag/v0.1.4).
