### ISSUE TITLE
Tray icon reflects sync state

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-community-gui#11]
This is easier to implement than a tray icon with a overlay and much better visible. Dropbox does this now too. We still have to think of the color code we should use. I think dropbox uses blue for synchronizing and white for done synchronizing. We could implement a similar strategy.  @Eliomendes , could you provide us with a blue tray icon, thanks.

**Comment by kaloyan-raev** [comment]
@MeijeSibbel Currently, we use https://drive.google.com/open?id=0B2kLTzlKaUqsSERLU0JZWDllNGs for the idle state and https://drive.google.com/open?id=0B2kLTzlKaUqsdWVLVi1zZlhyWXM for the synchronizing state.

What's the exact difference you want to introduce?

**Comment by MeijeSibbel** [comment]
@kaloyan-raev , @jkawamoto , lets use these: https://github.com/GooBox/brand-design/tree/master/Tray-status-icons, black for Mac/Linux, white ones for Windows. If you need any other tray sync state icons let me know.

**Comment by jkawamoto** [comment]
Looks good! I think we also need colored icons for Windows 7.

**Comment by kaloyan-raev** [comment]
I miss "ok/idle" icons with no overlay.

We may also need a "warning" icon. It can be useful for states which are not erroneous, but the user may need to take an action, e.g. funds/subscription about the deplete/expire, conflicts that require manual resolution, etc.

**Comment by MeijeSibbel** [comment]
All tray icons are now complete :fireworks:, closing.
