### ISSUE TITLE
Sync-Storj doesn't start at first install 

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-community-gui#117]
### Versions

Replace the values below with your own:

- **GUI Version:** v0.1.5
- **Operating System:** windows 10
- **Storage provider selected:** Storj

Optional:

- **Current account balance:** <number of units>
- **Current wallet address:** <address>
- **Size of sync directory:** <... GB>
- **Number of files and folders in Sync directory:** <... files and ... folders>

### logs

[storj-sync (1).log](https://github.com/GooBox/goobox-community-gui/files/1837028/storj-sync.1.log)
[log (1).log](https://github.com/GooBox/goobox-community-gui/files/1837029/log.1.log)

### Expected Behavior

Please describe the program's expected behavior.

```
Sync-Storj starts
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Sync-storj does not start at first app install 
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by kaloyan-raev** [comment]
It seems to be cause by an issue in java-libstorj fixed with https://github.com/Storj/java-libstorj/commit/e3305abc5f8ce5e8e96184b84372220185afb899 in v0.8.1
