### ISSUE TITLE
Notify user when SIA funds run low, and when they run out

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-community-gui#13]
We should also not allow users to go above of the available funds and send a notification to settings -> notifications once they get close to using up all the funds.

**Comment by jkawamoto** [comment]
We can also notify it by https://www.npmjs.com/package/node-notifier

**Comment by MeijeSibbel** [comment]
Good one, that might be a better option.

**Comment by jkawamoto** [comment]
Currently, the GUI checks the user's wallet and notifies him/her when his/her funds are less than 20 (min. number of required contracts) * current fee (SC/contract). The threshold can be adjusted.

**Comment by jkawamoto** [comment]
https://github.com/GooBox/goobox-sync-sia/commit/7c521d5c809396fb678510cb1ff679a87c98ae1b updates the threshold and now the GUI notifies the user when his/her funds are less than x2 of contract fee.
