### ISSUE TITLE
ECONNRESET in setup

### ISSUE THREAD

**Issue by AlexeyALeonov** [GooBox/goobox-community-gui#138]
### Versions

Replace the values below with your own:

- **GUI Version:** v0.2.1
- **Operating System:** Ubuntu 17.10
- **Storage provider selected:** Storj

Optional:

- **Current account balance:** <number of units>
- **Current wallet address:** <address>
- **Size of sync directory:** <... GB>
- **Number of files and folders in Sync directory:** <... files and ... folders>

### logs

Please attach the following logs:

## windows

- `C:\Users\USER\AppData\Roaming\Goobox\<log>.log`
- `C:\Users\USER\AppData\Local\Goobox\Logs\<...>-sync.log`

## Mac

....

## Linux

...

### Expected Behavior

Please describe the program's expected behavior.

```
The setup process could be finished
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Get an error below
```
![goobox 2018-07-21 13-33-14](https://user-images.githubusercontent.com/26858949/43034888-823f0700-8ced-11e8-88f2-b623015da4d2.png)

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Checkout the 0.2.1 version and build it for Linux, as described in the #129
2. Run the dist/Goobox-0.2.1-x86_64.AppImage
3. Choose the Storj
4. Specify the login, password and key and press Next
5. The error above is appeared. 

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by MeijeSibbel** [comment]
Thanks for the feedback!

**Comment by jkawamoto** [comment]
I'll close this issue although it's not fixed because [java-libstorj](https://github.com/storj/java-libstorj) was archived and storj/java-libstorj#24 won't be fixed.
