### ISSUE TITLE
Empty tray icon appears in Windows

### ISSUE THREAD

**Issue by jkawamoto** [GooBox/goobox-community-gui#19]

**Comment by jkawamoto** [comment]
@MeijeSibbel, does this icon still appear? In my test environment (Windows 10 Home, 1709, 16299.192), there are no empty icons appear. So, I'd like to make sure this issue has been fixed or not.

**Comment by MeijeSibbel** [comment]
Sorry for the late reply. You are correct @jkawamoto , i think the issue is fixed, i haven't seen this issue in a few versions. If i find it again i will re-open this issue.
