### ISSUE TITLE
Issues with v0.0.2

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-community-gui#20]
windows 10 home, x64

1. Double clicking on `goobox.exe` does nothing (it does open a task manager process though).
2. executing `goobox.exe installer` opens a white screen, see screenshot below, including 3x task manager processes.

![image](https://user-images.githubusercontent.com/11735738/34365725-c5d92c2c-ea93-11e7-9262-8470cebfe071.png)

**Comment by MeijeSibbel** [comment]
Issue persists with the version you uploaded to slack.

**Comment by MeijeSibbel** [comment]
I don't know if this is useful info but if i call the app via `goobox.exe installer` in CMD and then close the CMD window, the electron app also closes. Thus if we execute `goobox.exe installer` the CMD keeps the process open. in v0.0.1 this was not the case, we could close the CMD window from which we called the app and nothing would happen. So this new version has a different behavior.

**Comment by jkawamoto** [comment]
Commit 1de0976af57f0c492e9623f6f796ad8cedd3be57 fixed this issue.
