### ISSUE TITLE
Chrome Dev Console is visible by default

### ISSUE THREAD

**Issue by kaloyan-raev** [GooBox/goobox-community-gui#23]
Today I launched the GUI for first time ever and I got dialogs appear with the Chrome Dev Console on by default. This is valid for both the Installer and the Tray Popup. See the attached screenshots.

I could easily close the dev console by clicking on the X button, but it's quite confusing to have it.

![goobox-installer-dev-console](https://user-images.githubusercontent.com/468091/34516838-38362ff2-f081-11e7-986b-8a5c5219f511.png)

![goobox-tray-popup-dev-console](https://user-images.githubusercontent.com/468091/34516864-51d1a4d2-f081-11e7-929a-63076ba4590b.png)

**Comment by MeijeSibbel** [comment]
Yeah this is just for debugging purposes for now, it should definitely not come like that as default in the main releases. We should remove it (or make it optional like a setting) once we have a stable version that is ready for release.

**Comment by kaloyan-raev** [comment]
Perhaps, have a command line option like `-devconsole`.

**Comment by MeijeSibbel** [comment]
good idea^

**Comment by jkawamoto** [comment]
FYI: NODE_ENV=production disables the dev tools.
