### ISSUE TITLE
Problem with space in the sync folder path

### ISSUE THREAD

**Issue by kaloyan-raev** [GooBox/goobox-community-gui#25]
I have setup the Goobox sync folder to `C:\Users\John Doe\Goobox'. If I try to open the sync folder from the GUI, I get the following error:

![goobox-sync-folder-with-spaces](https://user-images.githubusercontent.com/468091/34517194-b5ee4c3a-f082-11e7-81f4-6d0fc292088a.png)

**Comment by jkawamoto** [comment]
openDirectory in util should quote dir.

**Comment by kaloyan-raev** [comment]
As @MeijeSibbel reported in Slack, there is now a slightly different error:

![goobox-sync-folder-with-spaces-2](https://user-images.githubusercontent.com/468091/34651545-37576f36-f3da-11e7-870c-467f133e42af.png)
