### ISSUE TITLE
Implement Storj login error screen

### ISSUE THREAD

**Issue by jkawamoto** [GooBox/goobox-community-gui#29]
https://app.zeplin.io/project.html#pid=5a1c52efaec36639118bd8b7&sid=5a51150a1bdccbbd087b23dc

**Comment by MeijeSibbel** [comment]
Right now it gives this popup instead of being handled by the electron app:

![image](https://user-images.githubusercontent.com/11735738/34749161-32022e0a-f5a0-11e7-8384-13b494a3a398.png)

**Comment by jkawamoto** [comment]
It hasn't been merged to master yet but commit c789804 fixed this issue, so I'll close it.
