### ISSUE TITLE
Implement tray-icon pop-up menu

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-community-gui#3]
When a user clicks on the tray icon once a window should appear as demonstrated below that shows a summary of the user's account/activity.

![layout](https://user-images.githubusercontent.com/11735738/33225127-3fc0d638-d172-11e7-8495-bd105308d7b0.png)

**Comment by MeijeSibbel** [comment]
As a summary from the discussion on github, it might be easier to implement this with electron instead of natively with Java. Here are some references to implementing this with electron:

https://www.bytcode.com/articles/1
https://electronjs.org/docs/api/menu
https://stackoverflow.com/questions/40485102/rich-html-tray-menu-in-a-desktop-web-application
https://xwartz.gitbooks.io/electron-gitbook/content/en/api/tray.html
https://github.com/electron/electron/blob/master/docs/api/tray.md

**Comment by jkawamoto** [comment]
Commit a75c147bd5977aac519169939449fa8a912ef39a implements tray-icon and pop-up window. This issue will be closed when that commit is merged to master.
