### ISSUE TITLE
Set the sync-dir folder icons

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-community-gui#35]
Icons can be found here: https://github.com/GooBox/brand-design/tree/master/sync_dir_icons. I discussed about this with @kaloyan-raev a few days ago.

**Comment by jkawamoto** [comment]
@kaloyan-raev, is the native installer going to implement this one?

**Comment by kaloyan-raev** [comment]
The installer has to register the overlay icon dlls in the windows registry. My initial idea was to have a native installer for this. But now as we have the electron installer doing everything, it worth a check if it can also register dlls. If it can then there will be no need of a native installer.

Do you know if this is possible?

**Comment by jkawamoto** [comment]
I think it is possible. The electron installer can execute .bat files and PowerShell scripts. Currently sync-storj app has .bat files to register/unregister dlls. So, if it is enough to call those bat files, the  installer can do.

**Comment by MeijeSibbel** [comment]
You have to run the script(s) as admin though otherwise it won't register the dlls.

**Comment by jkawamoto** [comment]
That's true. I fond a sample command to open a notepad as admin, 

```
powershell -NoProfile -ExecutionPolicy unrestricted -Command "start notepad C:\Windows\System32\drivers\etc\hosts -verb runas"
```

Let me check the installer can execute the above command.

**Comment by kaloyan-raev** [comment]
I found this node package that features elevation of permissions: https://www.npmjs.com/package/node-windows

It may be helpful for this case.

**Comment by jkawamoto** [comment]
New URL for the icon https://github.com/GooBox/brand-design/blob/master/Mockups/community_gui/prototype_one/sync_dir_icons/windows%20goobox.ico
