### ISSUE TITLE
Disable or hide the default sync-storj tray icon and menu

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-community-gui#37]
Since the GUI already has a menu and tray icon we shouldn't have a second one.

![image](https://user-images.githubusercontent.com/11735738/34749097-db02658e-f59f-11e7-8433-0f7f01e50f8c.png)

**Comment by kaloyan-raev** [comment]
I'll remove it in the next version of the storj sync app and will make it report icon updates to the GUI.

**Comment by kaloyan-raev** [comment]
https://github.com/GooBox/goobox-sync-storj/pull/77
