### ISSUE TITLE
Check seed compatibility with sync-storj

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-community-gui#38]
If a user logs in from another machine with a password and email address but uses a wrong seed, the app won't be able to decrypt the bucket or decrypt the files, which will result in errors. The app should check if it can decrypt the bucket or not, if it can't, it should prompt the user that he or she entered a wrong seed and should try entering the correct seed,

**Comment by MeijeSibbel** [comment]
To add to this, if a login once right now with the incorrect seed i can finish the install process just fine, it starts the sync-storj app but as it can't access the bucket it will never start synchronizing.

**Comment by kaloyan-raev** [comment]
There are two validations that can be implemented:
- as you type - checking the mnemonic integrity - if the correct dictionary words are used.
- bridge check - try listing the buckets and see if at least one can be decrypted with the provided mnemonic.

**Comment by jkawamoto** [comment]
We can also validate given mnemonic codes by [bitcoinj](https://github.com/bitcoinj/bitcoinj/blob/b6360e085821398c7495027a7b7254428c7592b0/core/src/main/java/org/bitcoinj/crypto/MnemonicCode.java#L237) etc.

**Comment by kaloyan-raev** [comment]
libstorj already provides the necessary check function. No need to introduce dependencies to new libraries.

**Comment by jkawamoto** [comment]
Sounds good. So, should we use that function to check the mnemonic integrity? But, I think bridge check is better. Otherwise, users get a kind of login error (encryption key mismatch) after successful login message.

**Comment by kaloyan-raev** [comment]
I suggest to have both. The integrity check is quick and can provide feedback to users before clicking the Finish button. When the Finish button is clicked the sync app will connect to the bridge and will verify all of the user, pass and encryption key.

**Comment by jkawamoto** [comment]
Got it. I'll implement a validation for encryption keys.

**Comment by kaloyan-raev** [comment]
I suggest to have a new `checkMnemonic` method to the GUI protocol. It should be called when the Encryption Key field in the installer changes.

The existing `login` method will provide the bridge check of the encryption key when the Finish button is clicked.

**Comment by jkawamoto** [comment]
Do you mean sync storj app has checkMnemonic method and GUI calls it when the user updates the encryption key? 

If checkMnemonic checks whether the encryption key consists of the correct dictionary words or not, I think GUI process should have checkMnemonic in order to reduce IPC communication cost.

**Comment by kaloyan-raev** [comment]
Yes, exactly.

IPC over pipe is quite cheap. You should not worry about performance. For example, IDEs and editors are moving towards the language server protocol concept where all the intellisense is provided by a background processes over pipe communication. Just like we do with the GUI and sync apps.

**Comment by jkawamoto** [comment]
Okay and we can also use checkMnemonic in the configuration screen when users re-login to Storj or update their login information, can't we?

According to the schemas of other requests, I think the schema of checkMnemonic requests is 
```
{
  method: "checkMnemonic",
  args: {
    encryptionKey: <mnemonic phrase>,
  }
}
```
and the schema of responses is 
```
{
  status: <ok|error>
  message: <message if necessary>
}
```
Do they have enough information?

**Comment by kaloyan-raev** [comment]
Yes, this should be enough.

**Comment by kaloyan-raev** [comment]
The `checkMnemonic` command is implemented with https://github.com/GooBox/goobox-sync-storj/pull/76

I will implement the bridge check later.

**Comment by kaloyan-raev** [comment]
The bridge check is implemented with https://github.com/GooBox/goobox-sync-storj/pull/85
