### ISSUE TITLE
Failed to login to Storj: timed out

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-community-gui#40]
![image](https://user-images.githubusercontent.com/11735738/34752608-a02a7154-f5b3-11e7-9c1e-3e4b20ee9bcb.png)

**Comment by kaloyan-raev** [comment]
If you had the auth file already available before executing this, you may be hitting the crash in #39, but just having a different reaction from the GUI.

**Comment by kaloyan-raev** [comment]
This is actually a different issue then #39. Again it is in the JNI code of java-libstorj. The request for validating the credentials is blocked in the libuv queue as there is synchronization going on at the moment and the queue is busy.

Again the workaround is to delete the auth file before running the Goobox installer.

**Comment by kaloyan-raev** [comment]
I cannot find a stable solution for this multi-threading issue.

As discussed in Slack, I added `--reset-auth-file` CLI option to the Storj app.

@jkawamoto this option is now available in the [0.0.15](https://github.com/GooBox/goobox-sync-storj/releases/tag/0.0.15) release. Please use it in the GUI and close this issue.

**Comment by jkawamoto** [comment]
@kaloyan-raev, thanks!
