### ISSUE TITLE
Register DLLs in Windows Installer

### ISSUE THREAD

**Issue by jkawamoto** [GooBox/goobox-community-gui#57]
https://stackoverflow.com/questions/47050866/nsis-register-dll-with-regsvr32
https://stackoverflow.com/questions/7618171/not-able-to-register-my-64bit-dll-through-nsis-script

**Comment by MeijeSibbel** [comment]
https://social.msdn.microsoft.com/Forums/en-US/942dfb5a-3d45-4e29-b6db-dd45fee16653/registering-32-bit-dll-on-windows-7-64-bit-during-installation-of-package-created-using?forum=visualfoxprogeneral

http://forums.winamp.com/showthread.php?t=348323
