### ISSUE TITLE
After uninstallation not all program files are removed on windows.

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-community-gui#63]
These include: `C:\Program Files\Goobox\resources\app\node_modules\bl\node_modules\readable-stream\doc`

and 

All the overlays in `C:\Program Files\Goobox\resources\libraries`

If this is intentional please close this issue.

**Comment by jkawamoto** [comment]
Good catch. After the DLLs are loaded successfully, they seem to require to reboot PC in order to delete them. Commit f0a007e might fix it (Since, In my PC, still failing to load DLLs, later I'll test it and close this issue)

**Comment by MeijeSibbel** [comment]
Thanks!, closing.

**Comment by MeijeSibbel** [comment]
Shoot, sorry.

**Comment by jkawamoto** [comment]
In my environment, it looks fixed.
