### ISSUE TITLE
Add `generate' seed button at Storj login screen.

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-community-gui#67]
Some users might have a Storj account already but don't have a seed, because they registered through app.storj.io. Adding a simple `Generate` button next to encryption key will allow people to generate one.

**Comment by jkawamoto** [comment]
I think we should implement a new GUI-sync storj IPC method "createSeed", or something like that.

**Comment by kaloyan-raev** [comment]
The `generateMnemonic` command is implemented with https://github.com/GooBox/goobox-sync-storj/pull/104

**Comment by kaloyan-raev** [comment]
Closed it by accidence. Reopening. The GUI still needs to implement the button.

**Comment by jkawamoto** [comment]
I'll implement the button when implementing the 2nd version of the GUI.
