### ISSUE TITLE
Fade or remove  "settings" button, or add blank windows in the GUI to avoid confusion 

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-community-gui#74]
Many people complained that the settings button did not work, of course, as there is nothing there yet. It came to my attention that this is frustrating people, so we should fix this before we start promoting the app. Maybe adding a blank settings menu is the easiest solution.

**Comment by jkawamoto** [comment]
Should we hide import drive button for now, too?

**Comment by MeijeSibbel** [comment]
I think on both, not rescaling when pressing on them should be enough.

**Comment by jkawamoto** [comment]
Hiding buttons by CSS is easier and now the popup looks like
![hide buttons](https://user-images.githubusercontent.com/1793096/35754285-eceb7f6c-0830-11e8-88c2-1fe702b1d663.png)

**Comment by MeijeSibbel** [comment]
Looks good
