### ISSUE TITLE
Installer is blocked by SmartScreen in Windows 10

### ISSUE THREAD

**Issue by AlexeyALeonov** [GooBox/goobox-community-gui#79]
Windows system is protected your computer 
The filter SmartScreen of Windows defender is prevent to start unknown application, which can harm your computer
![image](https://user-images.githubusercontent.com/26858949/35876050-30c15c58-0b82-11e8-93a5-6a27ee05f7b6.png)

**Comment by MeijeSibbel** [comment]
https://github.com/GooBox/goobox-community-gui/issues/26 shoudl fix that.

**Comment by MeijeSibbel** [comment]
Lets follow this issue in the original one i mentioned above.
