### ISSUE TITLE
Don't log email, password and encryptionkey

### ISSUE THREAD

**Issue by TopperDEL** [GooBox/goobox-community-gui#83]
Goobox logs the email, Password and the encryptionkey for storj into the Standard-logfile. I see this as a security hole. Is this really necessary?

**Comment by kaloyan-raev** [comment]
Thanks for reporting. It was helpful during development, but we really need to filter sensitive data in logs. This will be fixed shortly.

**Comment by kaloyan-raev** [comment]
Fixed with https://github.com/GooBox/goobox-sync-storj/pull/100
