### ISSUE TITLE
Display Sia/Storj account details under "account" section in settings.

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-community-gui#89]
Right now if a user just clicks next on the wallet screen without copying the seed or wallet address, they won't be able to easily find these details again without manually opening the `goobox.properties` file. We should display their account details under settings in the "account" section. Maybe we should also think about protecting these settings. The same applies if someone selects Storj.

**Comment by jkawamoto** [comment]
Related to #5

**Comment by jkawamoto** [comment]
I'm also planning to move goobox.properties to some secure/protected place, after settings are implemented.

**Comment by MeijeSibbel** [comment]
Lets continue following this here: https://github.com/GooBox/goobox-community-gui/issues/5
