### ISSUE TITLE
Set pop-up sia balance indication to integers

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-community-gui#91]
For some people 157,7000 indicates 158. We should just round this up to a integer number.

**Comment by jkawamoto** [comment]
Does the pop-up mean the notifications such as "Should have more than 100.000 SC" and "Allocated 10.500 SC"?

**Comment by MeijeSibbel** [comment]
Yes :)

**Comment by jkawamoto** [comment]
This issue has been fixed in https://github.com/GooBox/goobox-sync-sia/commit/893c3fd15764dfff9ed566499c0edbfae1cac001.
