### ISSUE TITLE
Desktop and Taskbar disappear during installation

### ISSUE THREAD

**Issue by betaboot** [GooBox/goobox-community-gui#96]
I'm using Win10, 64bit on a non-admin account.

When i double-click the installation file i first get a prompt for administration privileges. After entering the pw i get the Licence Agreement window and after that it starts installation. The moment installation is finished the desktop icons and taskbar disappear. I can go on with Goobox setup but desktop and taskbar don't come back. I have to reboot my pc to fix it.

**Comment by jkawamoto** [comment]
Thank you for reporting it. It seems the installer failed to restart Windows explorer.

**Comment by MeijeSibbel** [comment]
Lets continue following this in https://github.com/GooBox/goobox-community-gui/issues/106 as both issues occur due to the same root cause.
